# Generated by Django 3.0.8 on 2020-07-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='año',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
